# Define a versão da API do Kubernetes usada para este tipo de recurso
apiVersion: apps/v1

# Define o tipo de recurso que será criado (um controlador de implantação de Pods)
kind: Deployment

# Dados de identificação do Deployment
metadata:
  # Nome único do Deployment dentro do namespace
  name: php-apache

# Especificações sobre como o Deployment deve se comportar
spec:
  # Define como o Deployment encontra os Pods que ele deve gerenciar
  selector:
    matchLabels:
      # Procura por Pods que tenham a etiqueta (label) "run: php-apache"
      run: php-apache

  # Modelo (template) usado para criar os novos Pods
  template:
    metadata:
      # Etiquetas atribuídas aos novos Pods criados a partir deste modelo
      labels:
        # Etiqueta que faz o selector (acima) encontrar estes Pods
        run: php-apache

    # Especificações de infraestrutura e execução dos containers dentro do Pod
    spec:
      # Lista de containers que vão rodar dentro deste Pod
      containers:
      # Nome do container individual
      - name: php-apache
        # Imagem Docker/container que será baixada e executada da internet
        image: registry.k8s.io/hpa-example
        
        # Mapeamento de portas do container
        ports:
        # Porta interna na qual a aplicação do container escuta (porta 80 = HTTP)
        - containerPort: 80
        
        # Definições de limites e reservas de recursos de hardware
        resources:
          # Limite MÁXIMO de uso permitido para o container
          limits:
            # No máximo 500 millicores de CPU (equivalente a 0.5 núcleo de processador)
            cpu: 500m
          # Quantidade MÍNIMA reservada para o container conseguir iniciar
          requests:
            # Reserva 200 millicores de CPU (equivalente a 0.2 núcleo de processador)
            cpu: 200m

# Separador de documentos YAML (permite criar múltiplos recursos no mesmo arquivo)
---

# Versão da API principal do Kubernetes para recursos de rede básicos
apiVersion: v1

# Defines o tipo de recurso (um Serviço para expor a aplicação na rede interna)
kind: Service

# Dados de identificação do Service
metadata:
  # Nome do serviço (usado como endereço DNS interno no cluster: http://php-apache)
  name: php-apache
  # Etiquetas para organizar/identificar o recurso Service
  labels:
    run: php-apache

# Especificações sobre as regras de rede do Service
spec:
  # Configurações das portas de rede expostas pelo serviço
  ports:
  # Porta interna do cluster por onde o serviço receberá tráfego
  - port: 80

  # Mecanismo que conecta o Service aos Pods corretos
  selector:
    # Encaminha todo o tráfego que chega na porta 80 do Service 
    # para os Pods que possuem a etiqueta "run: php-apache"
    run: php-apache